defaults:
  box: ubuntu/wily64
  ram: 1024
  cpus: 1
masters:
  - hostname: amp
    enabled: true
    ip: 10.10.100.101
    box: ubuntu/xenial64
    ram: 2048
    cpus: 2
    # sync_folders:
    #   - source: /Users/mark/Workspaces/vagrant/file-store
    #     destination: /file-store
    shell:
      - echo "--AMP D/L START--"; curl -s -L "http://downloads.cloudsoftcorp.com/amp/latest/cloudsoft-amp-karaf-latest-all.deb" -o cloudsoft-amp-karaf.deb; echo "--AMP D/L COMPLETE--"
      - export DEBIAN_FRONTEND=noninteractive; sudo apt-get update; sudo apt-get install --yes default-jre-headless
      - sudo dpkg -i cloudsoft-amp-karaf.deb
      - sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8081
      - sudo chmod a+rw -R /opt/amp; sudo usermod -a -G amp ubuntu
      - sed -i -E 's/^#brooklyn\.webconsole\.security/brooklyn.webconsole.security/g' /opt/amp/etc/brooklyn.cfg
      - sudo systemctl restart amp
minions:
  - hostname: minion1
    ip: 10.10.100.101
    box: ubuntu/wily64
    ram: 2048
    cpus: 2
  - hostname: minion2
    ip: 10.10.100.102
    box: ubuntu/wily64
    ram: 2048
    cpus: 2
  - hostname: minion3
    ip: 10.10.100.103
    box: ubuntu/wily64
    ram: 2048
    cpus: 2
