defaults:
  box: ubuntu/wily64
  ram: 512
  cpus: 1
masters:
  - hostname: brooklyn-latest
    enabled: true
    ip: 10.10.100.101
    box: ubuntu/wily64
    ram: 2048
    cpus: 2
    shell:
    - curl -s -L "https://repository.apache.org/service/local/artifact/maven/redirect?r=snapshots&g=org.apache.brooklyn&a=brooklyn-dist&v=LATEST&p=tar.gz&c=dist" -o brooklyn-dist.tar.gz
    - tar -xvf brooklyn-dist.tar.gz; rm brooklyn-dist.tar.gz
    - mv /home/vagrant/brooklyn-dist-* /home/vagrant/brooklyn-dist; ln -s /home/vagrant/brooklyn-dist /home/vagrant/active-brooklyn
    - export DEBIAN_FRONTEND=noninteractive; sudo apt-get update;
    - sudo apt-get install --yes openjdk-8-jre-headless
    - sudo ln -s /vagrant/file-store/brooklyn.service /etc/systemd/system/brooklyn.service
    - mkdir -p /home/vagrant/.brooklyn
    - cp /vagrant/file-store/brooklyn.properties /home/vagrant/.brooklyn/
    - chmod 600 /home/vagrant/.brooklyn/brooklyn.properties
    - sudo systemctl start brooklyn
    - sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8081
  - hostname: qa-scheduler
    enabled: false
    ip: 10.10.200.201
    box: ubuntu/wily64
    ram: 2048
    cpus: 2
    sync_folders:
      - source: /Users/mark/.m2
        destination: /dot-m2
    shell:
    - sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8081
    - mkdir active-brooklyn
    - unzip /dot-m2/repository/io/cloudsoft/amp/qa-test-dist/1.0-SNAPSHOT/qa-test-dist-1.0-SNAPSHOT-dist.zip -d /home/vagrant/active-brooklyn
    - export DEBIAN_FRONTEND=noninteractive; sudo apt-get update;
    - sudo apt-get install --yes openjdk-8-jre-headless
    - sudo ln -s /vagrant/file-store/brooklyn.service /etc/systemd/system/brooklyn.service
    - mkdir -p /home/vagrant/.brooklyn
    - cp /vagrant/file-store/brooklyn.properties /home/vagrant/.brooklyn/
    - chmod 600 /home/vagrant/.brooklyn/brooklyn.properties
    - sudo systemctl start brooklyn
minions:
  - hostname: minion1
    ip: 10.10.100.101
    box: ubuntu/xenial64
  - hostname: minion2
    ip: 10.10.100.102
    box: ubuntu/xenial64
  - hostname: minion3
    ip: 10.10.100.103
    box: ubuntu/xenial64
