defaults:
  box: ubuntu/wily64
  ram: 1024
  cpus: 1
masters:
  - hostname: amp
    enabled: true
    ip: 10.10.100.101
    box: ubuntu/xenial64
    ram: 2048
    cpus: 2
    # sync_folders:
    #   - source: /Users/mark/Workspaces/vagrant/file-store
    #     destination: /file-store
    shell:
      - curl -s -L "https://artifactory.cloudsoftcorp.com/artifactory/libs-release-local/io/cloudsoft/amp/cloudsoft-amp-karaf/4.0.0-20160826.1547/cloudsoft-amp-karaf-4.0.0-20160826.1547-all.deb" -o cloudsoft-amp-karaf.deb
      - export DEBIAN_FRONTEND=noninteractive; sudo apt-get update;
      # - sudo apt-get install --yes openjdk-8-jre-headless
      - sudo apt-get install --yes default-jre-headless
      - sudo dpkg -i cloudsoft-amp-karaf.deb
      - sudo echo "brooklyn.webconsole.security.users=admin" >> /opt/amp/etc/brooklyn.cfg
      - sudo echo "brooklyn.webconsole.security.user.admin.password=password" >> /opt/amp/etc/brooklyn.cfg
      - sudo systemctl restart amp
      - sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8081
minions:
  - hostname: minion1
    ip: 10.10.100.101
    box: ubuntu/wily64
    ram: 2048
    cpus: 2
  - hostname: minion2
    ip: 10.10.100.102
    box: ubuntu/wily64
    ram: 2048
    cpus: 2
  - hostname: minion3
    ip: 10.10.100.103
    box: ubuntu/wily64
    ram: 2048
    cpus: 2
